apiVersion: apps/v1
kind: Deployment
metadata:
  name: o2ims-operator
  namespace: o2ims
  labels:
    app.kubernetes.io/name: nephio-o2ims
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nephio-o2ims
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nephio-o2ims
    spec:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65535
        runAsUser: 65535
      containers:
      - name: nephio-o2ims
        image: docker.io/nephio/o2ims-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: 'UPSTREAM_PKG_REPO'
          value: 'catalog-infra-capi'
        - name: 'KUBERNETES_BASE_URL'
          value: 'https://kubernetes.default.svc'
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: o2ims-operator
      terminationGracePeriodSeconds: 5
