apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-repo-secret-template-cm
  namespace: default
data:
  # The 'template.yaml' key holds the blueprint for our final secret
  template.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      # The name will be set dynamically in the job
      name: "__SECRET_NAME__"
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    type: Opaque
    stringData:
      type: git
      url: "__REPO_URL__"
      username: "__GIT_USERNAME__"
      password: "__ACCESS_TOKEN__"
