apiVersion: batch/v1
kind: Job
metadata:
  name: create-argocd-repo-secret-from-porch
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: argocd-secret-manager-sa
      containers:
      - name: kubectl-transformer
        image: bitnami/kubectl:latest
        command:
        - "/bin/sh"
        - "-c"
        - |
          set -e
          echo "INFO: Reading credentials from access-token secret..."
          
          # Read the access token from the mounted secret file.
          GIT_USERNAME=$(cat /etc/source-creds/username)
          ACCESS_TOKEN=$(cat /etc/source-creds/token)
          SECRET_TEMPLATE=$(cat /etc/templates/template.yaml) 

          if [ -z "$GIT_USERNAME" ]; then
            echo "ERROR: Username not found or is empty in the source secret."
            exit 1
          fi

          if [ -z "$ACCESS_TOKEN" ]; then
            echo "ERROR: Token not found or is empty in the source secret."
            exit 1
          fi

          echo "INFO: Generating Argo CD repository secret manifest for $REPO_URL..."

          # Create the final Argo CD secret manifest using a HEREDOC.
 
          FINAL_SECRET_YAML=$(echo "$SECRET_TEMPLATE" \
            | sed "s|__GIT_USERNAME__|${GIT_USERNAME}|g" \
            | sed "s|__ACCESS_TOKEN__|${ACCESS_TOKEN}|g")

          echo "INFO: Applying the final generated secret..."
          echo "$FINAL_SECRET_YAML" | kubectl apply -f -

          echo "INFO: Job complete. Argo CD repository secret created/updated."
        volumeMounts:
        - name: source-creds-vol
          mountPath: /etc/source-creds
          readOnly: true
        - name: template-vol
          mountPath: /etc/templates
          readOnly: true
      volumes:
      - name: source-creds-vol
        secret:
          secretName: example-cluster-name-access-token
          items:
          - key: username
            path: username
          - key: token
            path: token
      - name: template-vol
        configMap:
          name: argocd-repo-secret-template-cm
      restartPolicy: Never
  backoffLimit: 2
