apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cluster-secret-template
  namespace: default
data:
  # The key 'template.yaml' holds the blueprint for our final secret.
  template.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: cluster
    type: Opaque
